### PR TITLE
*: Fix TiDB compile error

### PR DESCRIPTION
**Pull request by shenli**
Fix: https://github.com/go-xorm/tidb/issues/3
@lunny  PTAL

### CODE REVIEW

**Comment by lunny** [comment]
I merged but `go test` failed. The log is below,

```
-------------- insertAutoIncr --------------
[xorm] [info]  2016/03/22 13:15:10.639783 [sql] INSERT INTO `userinfo` (`username`,`departname`,`created`,`detail_id`,`height`,`avatar`,`is_man`) VALUES (?, ?, ?, ?, ?, ?, ?) [args] [xiaolunwen2 dev 2016-03-22 13:15:10 1 1.78 [1 2 3] true]
2016/03/22 13:15:10 txn.go:128: [warning] [kv] Rollback txn 382369454001487873
0
--- FAIL: TestTidbGoLevelDBNoCache (1.05s)
    testInsert.go:58: INSERT INTO userinfo: expected 7 value(s), have 8
panic: INSERT INTO userinfo: expected 7 value(s), have 8 [recovered]
    panic: INSERT INTO userinfo: expected 7 value(s), have 8
```

**Comment by ngaut** [comment]
@shenli PTAL

**Comment by shenli** [comment]
@lunny I found the same panic yesterday and rise an issue: https://github.com/pingcap/tidb/issues/996
This is cause by a bug in TiDB. One of my colleague is working on this. It will be fixed soon.

**Comment by shenli** [comment]
@lunny We have fixed the bug in TiDB. I test this repo with the latest TiDB and xorm. It can pass go test.
PTAL

**Comment by lunny** [comment]
Great!

**Comment by insionng** [comment]
Thanks!

**Pull request merged**
